#!/bin/bash

# Retrieve the ACL bootstrap token from the respective Kubernetes secret and set it as an environment variable.
export CONSUL_HTTP_TOKEN=$(kubectl get --namespace consul secrets/consul-bootstrap-acl-token --template={{.data.token}} | base64 -d)

# Set the Consul destination address.
 export CONSUL_HTTP_ADDR=https://$(kubectl get services/consul-ui --namespace consul -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

# Remove SSL verification checks to simplify communication to your Consul cluster.
 export CONSUL_HTTP_SSL_VERIFY=false

 